export const GET_PROJECTS = "GET_PROJECTS";
export const ADD_PROJECT = "ADD_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const PROJECT_LOADING = "PROJECT_LOADING";
export const PROJECT_ERROR = "PROJECT_ERROR";
